name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - node: 20
            os: macos-latest
          - node: 20
            os: ubuntu-latest
          - node: 22
            os: windows-latest
          - node: 22
            os: ubuntu-latest
          - node: 22
            os: macos-latest
          - node: 24
            os: windows-latest
          - node: 24
            os: ubuntu-latest
          - node: 24
            os: macos-latest

    name: Test (node-${{ matrix.node }}/${{ matrix.os }})

    steps:
      - if: runner.os == 'Linux'  # PhantomJS OpenSSL 1.1.1 vs 3.x Ubuntu 22+ compat
        run: echo "OPENSSL_CONF=/dev/null" >> "$GITHUB_ENV"
      - if: runner.os == 'Windows'  # Tests would fail LF vs CRLF linebreak-style
        run: git config --global core.autocrlf false &&Â git config --global core.eol lf
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm test
